//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyRentalManagement_FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Apartment
    {
        public int ApartmentId { get; set; }


        [Required(ErrorMessage = "Apartment number is required")]
        [Display(Name = "Apartment Number")]
        public int ApartmentNumber { get; set; }

        [Required(ErrorMessage = "Apartments size is required")]
        public string Size { get; set; }

        [Required(ErrorMessage = "Please mention Included/Not Included for utilities")]
        public string Utility { get; set; }

        [Required(ErrorMessage = "Please mention the apartment rent")]
        public double Price { get; set; }

        [Required(ErrorMessage = "Please mention the availability of the apartment")]
        public string Availability { get; set; }
        public int BuildingId { get; set; }
    
        public virtual Building Building { get; set; }
    }
}
