//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyRentalManagement_FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Appointment
    {
        public int AppointmentId { get; set; }


        [Required(ErrorMessage = "Please enter your message")]
        [Display(Name = "Enter your message")]
        public string Description { get; set; }

        [Display(Name = "Set Appointment")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MMM/yyyy}")]
        public Nullable<System.DateTime> AppointmentDate { get; set; }


        [Required(ErrorMessage = "Please select one of the managers")]
        [Display(Name = "Select the manager")]
        public int ManagerId { get; set; }


        [Required(ErrorMessage = "Please select your name")]
        [Display(Name = "Select your name")]
        public int TenantId { get; set; }

        public string messageSuccess { get; set; }
        public string messageFailure { get; set; }

        public virtual Manager Manager { get; set; }
        public virtual Tenant Tenant { get; set; }
    }
}
